spring:
  profiles:
    active: localH2
  application:
    name: ApiContact
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mapping: true

---
spring:
  profiles: localH2
  datasource:
    url: jdbc:h2:mem:test;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id.new_generator_mappings: true
        show_sql: true
        use_sql_comments: true
        format_sql: true

---
spring:
  profiles: localPostgres
  datasource:
    url: jdbc:postgresql://localhost:5432/contact
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect


###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false